repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: mixed-line-ending
  - id: check-yaml
  - id: check-merge-conflict
  - id: check-added-large-files
    args: ['--maxkb=2000']
- repo: https://github.com/psf/black
  rev: 25.1.0
  hooks:
  - id: black
  - id: black-jupyter
- repo: https://github.com/aflc/pre-commit-jupyter
  rev: v1.2.1
  hooks:
  - id: jupyter-notebook-cleanup
- repo: https://github.com/snakemake/snakefmt
  rev: v0.10.2
  hooks:
  - id: snakefmt
