run: "default"

scenario:
  lt:
  - country+DE-elastic+true
  - country+DE-voll+true
  # - country+DE-inelastic+true
  st:
  - horizon+168-overlap+0
  - perfect_foresight+true-cyclic+true

country: DE

load: 100 # MW

voll: false
elastic: false
elastic_pwl: false # piecewise-linear
inelastic: false

voll_share: false # share of VoLL in demand

wind: true
solar: true

hydrogen: true
battery: true

dispatchable: false

elastic_intercept: 2000 # €/MWh
voll_price: 2000 # €/MWh

reserve: 0

elastic_pwl_params:
  default:
    intercept: [8000, 400, 200]
    slope: [80, 40, 20]
    nominal: [95, 5, 10]
  lower:
    intercept: [16000, 800, 400]
    slope: [160, 80, 40]
    nominal: [95, 5, 10]
  higher:
    intercept: [4000, 200, 100]
    slope: [40, 20, 10]
    nominal: [95, 5, 10]

cross_elasticity: false

cross_elasticity_params:
  default:
    extent: 4 # hours
    divisor: 16 # divisor of slope / b
  higher:
    extent: 4
    divisor: 8
  lower:
    extent: 4
    divisor: 24
  longer:
    extent: 8
    divisor: 16
  shorter:
    extent: 2
    divisor: 16
  lowest:
    extent: 4
    divisor: 64

number_years: false
random_years: true
fixed_year: false

zero_cost_storage: false

technology_data:
  year: 2030
  version: v0.8.1
  fill_values:
    FOM: 0
    VOM: 0
    efficiency: 1
    investment: 0
    lifetime: 25
    discount rate: 0.07
    fuel: 0
  overrides:
    electrolysis:
      investment: 1500 # €/kW
    hydrogen storage underground:
      investment: 0.15 # €/kWh


snapshots:
  start: "2020-01-01"
  end: "2021-01-01"
  inclusive: left
  freq: 1h

clip_p_max_pu: 1.e-2

cluster-sync:
    url: z1
    send-ignore: .syncignore-send
    receive-ignore: .syncignore-receive
    cluster-base-dir: SCRATCH/projects/price-formation
    custom-args: "" # e.g. -n for dry-run

solver:
  name: gurobi
  options: gurobi-default
  threads: 12
  mem_mb: 24000
  runtime: 12h

myopic_solver:
  name: gurobi
  threads: 2
  options: gurobi-default
  mem_mb: 8000
  runtime: 24h

solver_options:
  gurobi-default:
    method: 2
    crossover: 0
    BarConvTol: 1.e-8
    Seed: 123
    AggFill: 0
    PreDual: 0
    seed: 10
  gurobi-numeric:
    method: 2
    crossover: 0
    BarConvTol: 1.e-8
    NumericFocus: 1
    AggFill: 0
    PreDual: 0
  highs-default:
    run_crossover: "off"
    small_matrix_value: 1e-6
    large_matrix_value: 1e10
    primal_feasibility_tolerance: 1e-6
    dual_feasibility_tolerance: 1e-6
    ipm_optimality_tolerance: 1e-8
    parallel: "on"
    random_seed: 123

myopic:
  horizon: 72
  overlap: 48
  perfect_foresight: false
  cyclic: false
  battery_bid: "mean" # or 'mean' or float
  hydrogen_bid: "mean" # or 'mean' or float
  perturbation: 1 # pattern: <carrier: factor>
  number_years: false
  random_years: true

export_to_netcdf:
  float32: true
  compression:
    zlib: true
    complevel: 9
    least_significant_digit: 5

colors:
  total: "#555555"
  wind: "#0056B8"
  wind curtailed: "#add4ef"
  solar: "#FFD800"
  solar curtailed: "#e8d786"
  battery: "#6B8F80"
  battery storage: "#6B8F80"
  battery charger: "#6B8F80"
  battery discharger: "#6B8F80"
  battery dis-/charging: "#67A345"
  hydrogen: "#B8326A"
  hydrogen fuel cell: "#E17B36"
  hydrogen electrolyser: "#B83C69"
  hydrogen underground storage: "#A05AA7"
  hydrogen storage: "#A05AA7"
  electricity: "#6BA34A"
  load: "#6BA34A"
  load-shedding: "#bac7ad"

color_palette: colorblind

preferred_order:
  - load
  - hydrogen electrolyser
  - battery charger
  - wind
  - solar
  - hydrogen fuel cell
  - battery discharger
  - load-shedding
  - wind curtailed
  - solar curtailed

supply_demand_curve:
  snapshots: []
    # - 2010-07-01 00:00
  ylim_max: 2000
