run: "default"

scenario:
  lt:
  - country+DE-number_years+1-inelastic+true
  - country+DE-number_years+1-elastic+true-elastic_intercept+200
  - country+DE-number_years+1-elastic+true-elastic_intercept+2000
  - country+DE-number_years+1-elastic+true-elastic_intercept+20000
  - country+ES-number_years+1-inelastic+true
  - country+ES-number_years+1-elastic+true-elastic_intercept+200
  - country+ES-number_years+1-elastic+true-elastic_intercept+2000
  - country+ES-number_years+1-elastic+true-elastic_intercept+20000
  st:
  - number_years+1-horizon+96-overlap+24
  - number_years+1-horizon+96-overlap+24-perturbation+0.99
  - number_years+1-horizon+96-overlap+24-perturbation+1.01
  - number_years+1-horizon+72-overlap+24
  - number_years+1-horizon+48-overlap+24
  - number_years+1-perfect_foresight+true

country: DE

load: 100 # MW

voll: false
elastic: false
inelastic: false

voll_share: false # share of VoLL in demand

wind: true
solar: true

hydrogen: true
battery: true

elastic_intercept: 2000 # €/MWh
voll_price: 2000 # €/MWh

number_years: false
random_years: true

zero_cost_storage: false

technology_data:
  year: 2030
  version: v0.6.0
  fill_values:
    FOM: 0
    VOM: 0
    efficiency: 1
    investment: 0
    lifetime: 25
    discount rate: 0.07

snapshots:
  start: "1950-01-01"
  end: "2021-01-01"
  inclusive: left
  freq: 1H

cluster-sync:
    url: zecm
    send-ignore: .syncignore-send
    receive-ignore: .syncignore-receive
    cluster-base-dir: /scratch/fneum/projects/price-formation
    custom-args: "" # e.g. -n for dry-run

solver:
  name: gurobi
  options: gurobi-default
  mem_mb: 16000
  walltime: "24:00:00"

solver_options:
  gurobi-default:
    threads: 4
    method: 2 # barrier
    crossover: 0
    BarConvTol: 1.e-8
    Seed: 123
    AggFill: 0
    PreDual: 0
    GURO_PAR_BARDENSETHRESH: 200
    seed: 10

myopic:
  horizon: 72
  overlap: 48
  perfect_foresight: false
  cyclic: false
  battery_bid: "mean" # or 'mean' or float
  hydrogen_bid: "mean" # or 'mean' or float
  perturbation: 1 # pattern: <carrier: factor>
  number_years: false
  random_years: false

export_to_netcdf:
  float32: true
  compression:
    zlib: true
    complevel: 9
    least_significant_digit: 5

colors:
  wind: "#2b90d4"
  wind curtailed: "#add4ef"
  solar: "#d6b829"
  solar curtailed: "#e8d786"
  battery: "#758a85"
  battery storage: "#758a85"
  battery charger: "#758a85"
  battery discharger: "#758a85"
  hydrogen: "#ce317c"
  hydrogen fuel cell: "#e16d26"
  hydrogen electrolyser: "#ce317c"
  hydrogen underground storage: "#9723dc"
  hydrogen storage: "#9723dc"
  electricity: "#7eae51"
  load: "#7eae51"

preferred_order:
  - load
  - hydrogen electrolyser
  - battery charger
  - wind
  - solar
  - hydrogen fuel cell
  - battery discharger
  - wind curtailed
  - solar curtailed

supply_demand_curve:
  snapshots: []
    # - 2010-07-01 00:00
  ylim_max: 2000
