run: "20240506-num-years"

scenario:
  lt:
  - country+DE-number_years+1-inelastic+true
  - country+DE-number_years+2-inelastic+true
  - country+DE-number_years+4-inelastic+true
  - country+DE-number_years+8-inelastic+true
  - country+DE-number_years+10-inelastic+true
  - country+DE-number_years+16-inelastic+true
  - country+DE-number_years+20-inelastic+true
  - country+DE-number_years+30-inelastic+true
  - country+DE-number_years+32-inelastic+true
  - country+DE-number_years+40-inelastic+true
  - country+DE-number_years+48-inelastic+true
  - country+DE-number_years+60-inelastic+true
  - country+DE-number_years+64-inelastic+true
  - country+DE-number_years+70-inelastic+true
  - country+DE-number_years+1-voll+true
  - country+DE-number_years+2-voll+true
  - country+DE-number_years+4-voll+true
  - country+DE-number_years+8-voll+true
  - country+DE-number_years+10-voll+true
  - country+DE-number_years+16-voll+true
  - country+DE-number_years+20-voll+true
  - country+DE-number_years+30-voll+true
  - country+DE-number_years+32-voll+true
  - country+DE-number_years+40-voll+true
  - country+DE-number_years+48-voll+true
  - country+DE-number_years+60-voll+true
  - country+DE-number_years+64-voll+true
  - country+DE-number_years+70-voll+true
  - country+DE-number_years+1-elastic_pwl+default
  - country+DE-number_years+2-elastic_pwl+default
  - country+DE-number_years+4-elastic_pwl+default
  - country+DE-number_years+8-elastic_pwl+default
  - country+DE-number_years+10-elastic_pwl+default
  - country+DE-number_years+16-elastic_pwl+default
  - country+DE-number_years+20-elastic_pwl+default
  - country+DE-number_years+30-elastic_pwl+default
  - country+DE-number_years+32-elastic_pwl+default
  - country+DE-number_years+40-elastic_pwl+default
  - country+DE-number_years+48-elastic_pwl+default
  - country+DE-number_years+60-elastic_pwl+default
  - country+DE-number_years+64-elastic_pwl+default
  - country+DE-number_years+70-elastic_pwl+default
  - country+DE-number_years+1-elastic+true-elastic_intercept+2000
  - country+DE-number_years+2-elastic+true-elastic_intercept+2000
  - country+DE-number_years+4-elastic+true-elastic_intercept+2000
  - country+DE-number_years+8-elastic+true-elastic_intercept+2000
  - country+DE-number_years+10-elastic+true-elastic_intercept+2000
  - country+DE-number_years+16-elastic+true-elastic_intercept+2000
  - country+DE-number_years+20-elastic+true-elastic_intercept+2000
  - country+DE-number_years+30-elastic+true-elastic_intercept+2000
  - country+DE-number_years+32-elastic+true-elastic_intercept+2000
  - country+DE-number_years+40-elastic+true-elastic_intercept+2000
  - country+DE-number_years+48-elastic+true-elastic_intercept+2000
  - country+DE-number_years+60-elastic+true-elastic_intercept+2000
  - country+DE-number_years+64-elastic+true-elastic_intercept+2000
  - country+DE-number_years+70-elastic+true-elastic_intercept+2000
  - country+DE-number_years+1-elastic+true-elastic_intercept+200
  - country+DE-number_years+2-elastic+true-elastic_intercept+200
  - country+DE-number_years+4-elastic+true-elastic_intercept+200
  - country+DE-number_years+8-elastic+true-elastic_intercept+200
  - country+DE-number_years+10-elastic+true-elastic_intercept+200
  - country+DE-number_years+16-elastic+true-elastic_intercept+200
  - country+DE-number_years+20-elastic+true-elastic_intercept+200
  - country+DE-number_years+30-elastic+true-elastic_intercept+200
  - country+DE-number_years+32-elastic+true-elastic_intercept+200
  - country+DE-number_years+40-elastic+true-elastic_intercept+200
  - country+DE-number_years+48-elastic+true-elastic_intercept+200
  - country+DE-number_years+60-elastic+true-elastic_intercept+200
  - country+DE-number_years+64-elastic+true-elastic_intercept+200
  - country+DE-number_years+70-elastic+true-elastic_intercept+200
  - country+ES-number_years+1-inelastic+true
  - country+ES-number_years+2-inelastic+true
  - country+ES-number_years+4-inelastic+true
  - country+ES-number_years+8-inelastic+true
  - country+ES-number_years+10-inelastic+true
  - country+ES-number_years+16-inelastic+true
  - country+ES-number_years+20-inelastic+true
  - country+ES-number_years+30-inelastic+true
  - country+ES-number_years+32-inelastic+true
  - country+ES-number_years+40-inelastic+true
  - country+ES-number_years+48-inelastic+true
  - country+ES-number_years+60-inelastic+true
  - country+ES-number_years+64-inelastic+true
  - country+ES-number_years+70-inelastic+true
  - country+ES-number_years+1-voll+true
  - country+ES-number_years+2-voll+true
  - country+ES-number_years+4-voll+true
  - country+ES-number_years+8-voll+true
  - country+ES-number_years+10-voll+true
  - country+ES-number_years+16-voll+true
  - country+ES-number_years+20-voll+true
  - country+ES-number_years+30-voll+true
  - country+ES-number_years+32-voll+true
  - country+ES-number_years+40-voll+true
  - country+ES-number_years+48-voll+true
  - country+ES-number_years+60-voll+true
  - country+ES-number_years+64-voll+true
  - country+ES-number_years+70-voll+true
  - country+ES-number_years+1-elastic_pwl+default
  - country+ES-number_years+2-elastic_pwl+default
  - country+ES-number_years+4-elastic_pwl+default
  - country+ES-number_years+8-elastic_pwl+default
  - country+ES-number_years+10-elastic_pwl+default
  - country+ES-number_years+16-elastic_pwl+default
  - country+ES-number_years+20-elastic_pwl+default
  - country+ES-number_years+30-elastic_pwl+default
  - country+ES-number_years+32-elastic_pwl+default
  - country+ES-number_years+40-elastic_pwl+default
  - country+ES-number_years+48-elastic_pwl+default
  - country+ES-number_years+60-elastic_pwl+default
  - country+ES-number_years+64-elastic_pwl+default
  - country+ES-number_years+70-elastic_pwl+default
  - country+ES-number_years+1-elastic+true-elastic_intercept+2000
  - country+ES-number_years+2-elastic+true-elastic_intercept+2000
  - country+ES-number_years+4-elastic+true-elastic_intercept+2000
  - country+ES-number_years+8-elastic+true-elastic_intercept+2000
  - country+ES-number_years+10-elastic+true-elastic_intercept+2000
  - country+ES-number_years+16-elastic+true-elastic_intercept+2000
  - country+ES-number_years+20-elastic+true-elastic_intercept+2000
  - country+ES-number_years+30-elastic+true-elastic_intercept+2000
  - country+ES-number_years+32-elastic+true-elastic_intercept+2000
  - country+ES-number_years+40-elastic+true-elastic_intercept+2000
  - country+ES-number_years+48-elastic+true-elastic_intercept+2000
  - country+ES-number_years+60-elastic+true-elastic_intercept+2000
  - country+ES-number_years+64-elastic+true-elastic_intercept+2000
  - country+ES-number_years+70-elastic+true-elastic_intercept+2000
  - country+ES-number_years+1-elastic+true-elastic_intercept+200
  - country+ES-number_years+2-elastic+true-elastic_intercept+200
  - country+ES-number_years+4-elastic+true-elastic_intercept+200
  - country+ES-number_years+8-elastic+true-elastic_intercept+200
  - country+ES-number_years+10-elastic+true-elastic_intercept+200
  - country+ES-number_years+16-elastic+true-elastic_intercept+200
  - country+ES-number_years+20-elastic+true-elastic_intercept+200
  - country+ES-number_years+30-elastic+true-elastic_intercept+200
  - country+ES-number_years+32-elastic+true-elastic_intercept+200
  - country+ES-number_years+40-elastic+true-elastic_intercept+200
  - country+ES-number_years+48-elastic+true-elastic_intercept+200
  - country+ES-number_years+60-elastic+true-elastic_intercept+200
  - country+ES-number_years+64-elastic+true-elastic_intercept+200
  - country+ES-number_years+70-elastic+true-elastic_intercept+200
  - country+UK-number_years+1-inelastic+true
  - country+UK-number_years+2-inelastic+true
  - country+UK-number_years+4-inelastic+true
  - country+UK-number_years+8-inelastic+true
  - country+UK-number_years+10-inelastic+true
  - country+UK-number_years+16-inelastic+true
  - country+UK-number_years+20-inelastic+true
  - country+UK-number_years+30-inelastic+true
  - country+UK-number_years+32-inelastic+true
  - country+UK-number_years+40-inelastic+true
  - country+UK-number_years+48-inelastic+true
  - country+UK-number_years+60-inelastic+true
  - country+UK-number_years+64-inelastic+true
  - country+UK-number_years+70-inelastic+true
  - country+UK-number_years+1-voll+true
  - country+UK-number_years+2-voll+true
  - country+UK-number_years+4-voll+true
  - country+UK-number_years+8-voll+true
  - country+UK-number_years+10-voll+true
  - country+UK-number_years+16-voll+true
  - country+UK-number_years+20-voll+true
  - country+UK-number_years+30-voll+true
  - country+UK-number_years+32-voll+true
  - country+UK-number_years+40-voll+true
  - country+UK-number_years+48-voll+true
  - country+UK-number_years+60-voll+true
  - country+UK-number_years+64-voll+true
  - country+UK-number_years+70-voll+true
  - country+UK-number_years+1-elastic_pwl+default
  - country+UK-number_years+2-elastic_pwl+default
  - country+UK-number_years+4-elastic_pwl+default
  - country+UK-number_years+8-elastic_pwl+default
  - country+UK-number_years+10-elastic_pwl+default
  - country+UK-number_years+16-elastic_pwl+default
  - country+UK-number_years+20-elastic_pwl+default
  - country+UK-number_years+30-elastic_pwl+default
  - country+UK-number_years+32-elastic_pwl+default
  - country+UK-number_years+40-elastic_pwl+default
  - country+UK-number_years+48-elastic_pwl+default
  - country+UK-number_years+60-elastic_pwl+default
  - country+UK-number_years+64-elastic_pwl+default
  - country+UK-number_years+70-elastic_pwl+default
  - country+UK-number_years+1-elastic+true-elastic_intercept+2000
  - country+UK-number_years+2-elastic+true-elastic_intercept+2000
  - country+UK-number_years+4-elastic+true-elastic_intercept+2000
  - country+UK-number_years+8-elastic+true-elastic_intercept+2000
  - country+UK-number_years+10-elastic+true-elastic_intercept+2000
  - country+UK-number_years+16-elastic+true-elastic_intercept+2000
  - country+UK-number_years+20-elastic+true-elastic_intercept+2000
  - country+UK-number_years+30-elastic+true-elastic_intercept+2000
  - country+UK-number_years+32-elastic+true-elastic_intercept+2000
  - country+UK-number_years+40-elastic+true-elastic_intercept+2000
  - country+UK-number_years+48-elastic+true-elastic_intercept+2000
  - country+UK-number_years+60-elastic+true-elastic_intercept+2000
  - country+UK-number_years+64-elastic+true-elastic_intercept+2000
  - country+UK-number_years+70-elastic+true-elastic_intercept+2000
  - country+UK-number_years+1-elastic+true-elastic_intercept+200
  - country+UK-number_years+2-elastic+true-elastic_intercept+200
  - country+UK-number_years+4-elastic+true-elastic_intercept+200
  - country+UK-number_years+8-elastic+true-elastic_intercept+200
  - country+UK-number_years+10-elastic+true-elastic_intercept+200
  - country+UK-number_years+16-elastic+true-elastic_intercept+200
  - country+UK-number_years+20-elastic+true-elastic_intercept+200
  - country+UK-number_years+30-elastic+true-elastic_intercept+200
  - country+UK-number_years+32-elastic+true-elastic_intercept+200
  - country+UK-number_years+40-elastic+true-elastic_intercept+200
  - country+UK-number_years+48-elastic+true-elastic_intercept+200
  - country+UK-number_years+60-elastic+true-elastic_intercept+200
  - country+UK-number_years+64-elastic+true-elastic_intercept+200
  - country+UK-number_years+70-elastic+true-elastic_intercept+200
  - country+IE-number_years+1-inelastic+true
  - country+IE-number_years+2-inelastic+true
  - country+IE-number_years+4-inelastic+true
  - country+IE-number_years+8-inelastic+true
  - country+IE-number_years+10-inelastic+true
  - country+IE-number_years+16-inelastic+true
  - country+IE-number_years+20-inelastic+true
  - country+IE-number_years+30-inelastic+true
  - country+IE-number_years+32-inelastic+true
  - country+IE-number_years+40-inelastic+true
  - country+IE-number_years+48-inelastic+true
  - country+IE-number_years+60-inelastic+true
  - country+IE-number_years+64-inelastic+true
  - country+IE-number_years+70-inelastic+true
  - country+IE-number_years+1-voll+true
  - country+IE-number_years+2-voll+true
  - country+IE-number_years+4-voll+true
  - country+IE-number_years+8-voll+true
  - country+IE-number_years+10-voll+true
  - country+IE-number_years+16-voll+true
  - country+IE-number_years+20-voll+true
  - country+IE-number_years+30-voll+true
  - country+IE-number_years+32-voll+true
  - country+IE-number_years+40-voll+true
  - country+IE-number_years+48-voll+true
  - country+IE-number_years+60-voll+true
  - country+IE-number_years+64-voll+true
  - country+IE-number_years+70-voll+true
  - country+IE-number_years+1-elastic_pwl+default
  - country+IE-number_years+2-elastic_pwl+default
  - country+IE-number_years+4-elastic_pwl+default
  - country+IE-number_years+8-elastic_pwl+default
  - country+IE-number_years+10-elastic_pwl+default
  - country+IE-number_years+16-elastic_pwl+default
  - country+IE-number_years+20-elastic_pwl+default
  - country+IE-number_years+30-elastic_pwl+default
  - country+IE-number_years+32-elastic_pwl+default
  - country+IE-number_years+40-elastic_pwl+default
  - country+IE-number_years+48-elastic_pwl+default
  - country+IE-number_years+60-elastic_pwl+default
  - country+IE-number_years+64-elastic_pwl+default
  - country+IE-number_years+70-elastic_pwl+default
  - country+IE-number_years+1-elastic+true-elastic_intercept+2000
  - country+IE-number_years+2-elastic+true-elastic_intercept+2000
  - country+IE-number_years+4-elastic+true-elastic_intercept+2000
  - country+IE-number_years+8-elastic+true-elastic_intercept+2000
  - country+IE-number_years+10-elastic+true-elastic_intercept+2000
  - country+IE-number_years+16-elastic+true-elastic_intercept+2000
  - country+IE-number_years+20-elastic+true-elastic_intercept+2000
  - country+IE-number_years+30-elastic+true-elastic_intercept+2000
  - country+IE-number_years+32-elastic+true-elastic_intercept+2000
  - country+IE-number_years+40-elastic+true-elastic_intercept+2000
  - country+IE-number_years+48-elastic+true-elastic_intercept+2000
  - country+IE-number_years+60-elastic+true-elastic_intercept+2000
  - country+IE-number_years+64-elastic+true-elastic_intercept+2000
  - country+IE-number_years+70-elastic+true-elastic_intercept+2000
  - country+IE-number_years+1-elastic+true-elastic_intercept+200
  - country+IE-number_years+2-elastic+true-elastic_intercept+200
  - country+IE-number_years+4-elastic+true-elastic_intercept+200
  - country+IE-number_years+8-elastic+true-elastic_intercept+200
  - country+IE-number_years+10-elastic+true-elastic_intercept+200
  - country+IE-number_years+16-elastic+true-elastic_intercept+200
  - country+IE-number_years+20-elastic+true-elastic_intercept+200
  - country+IE-number_years+30-elastic+true-elastic_intercept+200
  - country+IE-number_years+32-elastic+true-elastic_intercept+200
  - country+IE-number_years+40-elastic+true-elastic_intercept+200
  - country+IE-number_years+48-elastic+true-elastic_intercept+200
  - country+IE-number_years+60-elastic+true-elastic_intercept+200
  - country+IE-number_years+64-elastic+true-elastic_intercept+200
  - country+IE-number_years+70-elastic+true-elastic_intercept+200
  st: []

snapshots:
  start: "1951-01-01"
  end: "2021-01-01"

solver:
  mem_mb: 40000
  walltime: 24h
  threads: 32
  options: gurobi-default
