run: "20240506-single"

scenario:
  lt:
  - country+DE-inelastic+true
  - country+DE-voll+true
  - country+DE-elastic_pwl+default
  - country+DE-elastic_pwl+lower
  - country+DE-elastic_pwl+higher
  - country+DE-elastic+true-elastic_intercept+200
  - country+DE-elastic+true-elastic_intercept+2000
  - country+DE-elastic+true-elastic_intercept+20000
  - country+DE-elastic+true-voll+true-elastic_intercept+2000-voll_share+0.9
  - country+DE-elastic+true-voll+true-elastic_intercept+2000-voll_share+0.5
  - country+DE-elastic+true-elastic_intercept+2000-zero_cost_storage+true-battery+false
  - country+DE-elastic_pwl+default-zero_cost_storage+true-battery+false
  - country+DE-voll+true-zero_cost_storage+true-battery+false
  - country+DE-inelastic+true-zero_cost_storage+true-battery+false
  - country+DE-elastic+true-elastic_intercept+2000-battery+false
  - country+DE-elastic_pwl+default-battery+false
  - country+DE-voll+true-battery+false
  - country+DE-inelastic+true-battery+false
  - country+ES-inelastic+true
  - country+ES-voll+true
  - country+ES-elastic_pwl+default
  - country+ES-elastic_pwl+lower
  - country+ES-elastic_pwl+higher
  - country+ES-elastic+true-elastic_intercept+200
  - country+ES-elastic+true-elastic_intercept+2000
  - country+ES-elastic+true-elastic_intercept+20000
  - country+ES-elastic+true-voll+true-elastic_intercept+2000-voll_share+0.9
  - country+ES-elastic+true-voll+true-elastic_intercept+2000-voll_share+0.5
  - country+ES-elastic+true-elastic_intercept+2000-zero_cost_storage+true-battery+false
  - country+ES-elastic_pwl+default-zero_cost_storage+true-battery+false
  - country+ES-voll+true-zero_cost_storage+true-battery+false
  - country+ES-inelastic+true-zero_cost_storage+true-battery+false
  - country+ES-elastic+true-elastic_intercept+2000-battery+false
  - country+ES-elastic_pwl+default-battery+false
  - country+ES-voll+true-battery+false
  - country+ES-inelastic+true-battery+false
  - country+UK-inelastic+true
  - country+UK-voll+true
  - country+UK-elastic_pwl+default
  - country+UK-elastic_pwl+lower
  - country+UK-elastic_pwl+higher
  - country+UK-elastic+true-elastic_intercept+200
  - country+UK-elastic+true-elastic_intercept+2000
  - country+UK-elastic+true-elastic_intercept+20000
  - country+UK-elastic+true-voll+true-elastic_intercept+2000-voll_share+0.9
  - country+UK-elastic+true-voll+true-elastic_intercept+2000-voll_share+0.5
  - country+UK-elastic+true-elastic_intercept+2000-zero_cost_storage+true-battery+false
  - country+UK-elastic_pwl+default-zero_cost_storage+true-battery+false
  - country+UK-voll+true-zero_cost_storage+true-battery+false
  - country+UK-inelastic+true-zero_cost_storage+true-battery+false
  - country+UK-elastic+true-elastic_intercept+2000-battery+false
  - country+UK-elastic_pwl+default-battery+false
  - country+UK-voll+true-battery+false
  - country+UK-inelastic+true-battery+false
  - country+IE-inelastic+true
  - country+IE-voll+true
  - country+IE-elastic_pwl+default
  - country+IE-elastic_pwl+lower
  - country+IE-elastic_pwl+higher
  - country+IE-elastic+true-elastic_intercept+200
  - country+IE-elastic+true-elastic_intercept+2000
  - country+IE-elastic+true-elastic_intercept+20000
  - country+IE-elastic+true-voll+true-elastic_intercept+2000-voll_share+0.9
  - country+IE-elastic+true-voll+true-elastic_intercept+2000-voll_share+0.5
  - country+IE-elastic+true-elastic_intercept+2000-zero_cost_storage+true-battery+false
  - country+IE-elastic_pwl+default-zero_cost_storage+true-battery+false
  - country+IE-voll+true-zero_cost_storage+true-battery+false
  - country+IE-inelastic+true-zero_cost_storage+true-battery+false
  - country+IE-elastic+true-elastic_intercept+2000-battery+false
  - country+IE-elastic_pwl+default-battery+false
  - country+IE-voll+true-battery+false
  - country+IE-inelastic+true-battery+false
  st:
  - horizon+96-overlap+24
  - horizon+72-overlap+24
  - horizon+48-overlap+24
  - horizon+24-overlap+12
  - horizon+96-overlap+24-perturbation+0.9
  - horizon+96-overlap+24-perturbation+0.95
  - horizon+96-overlap+24-perturbation+0.99
  - horizon+96-overlap+24-perturbation+1.01
  - horizon+96-overlap+24-perturbation+1.05
  - horizon+96-overlap+24-perturbation+1.1
  - horizon+96-overlap+24-hydrogen_bid+0-battery_bid+0
  - perfect_foresight+true
  - perfect_foresight+true-cyclic+true
  - perfect_foresight+true-hydrogen_bid+series-battery_bid+series
  - perfect_foresight+true-hydrogen_bid+series-battery_bid+series-cyclic+true
  - perfect_foresight+true-hydrogen_bid+0-battery_bid+0-cyclic+true

snapshots:
  start: "2020-01-01"
  end: "2021-01-01"

solver:
  mem_mb: 4000
  walltime: "01:00:00"

myopic_solver:
  mem_mb: 4000
  walltime: "01:00:00"
