country: DE

load: 100 # MW

voll: false
elastic: false
inelastic: true

wind: true
solar: true

hydrogen: true
battery: true

elastic_intercept: 2000 # €/MWh
voll_price: 2000 # €/MWh

zero_cost_storage: false

technology_data:
  year: 2030
  version: v0.6.0
  fill_values:
    FOM: 0
    VOM: 0
    efficiency: 1
    investment: 0
    lifetime: 25
    discount rate: 0.07

snapshots:
  start: "2010-01-01"
  end: "2011-01-01"
  inclusive: left
  freq: 1H

solver:
  name: gurobi
  options: gurobi-default

solver_options:
  gurobi-default:
    threads: 4
    method: 2 # barrier
    crossover: 0
    BarConvTol: 1.e-7
    Seed: 123
    AggFill: 0
    PreDual: 0
    GURO_PAR_BARDENSETHRESH: 200
    seed: 10


colors:
  wind: "#2b90d4"
  wind curtailed: "#add4ef"
  solar: "#d6b829"
  solar curtailed: "#e8d786"
  battery: "#758a85"
  battery storage: "#758a85"
  battery charger: "#758a85"
  battery discharger: "#758a85"
  hydrogen: "#ce317c"
  hydrogen fuel cell: "#e16d26"
  hydrogen electrolyser: "#ce317c"
  hydrogen underground storage: "#9723dc"
  electricity: "#7eae51"
  load: "#7eae51"

preferred_order:
  - load
  - hydrogen electrolyser
  - battery charger
  - wind
  - solar
  - hydrogen fuel cell
  - battery discharger
  - wind curtailed
  - solar curtailed