run: "20240506-fixed-years"

scenario:
  lt:
  - country+DE-fixed_year+1951-inelastic+true
  - country+DE-fixed_year+1951-voll+true
  - country+DE-fixed_year+1951-elastic_pwl+default
  - country+DE-fixed_year+1952-inelastic+true
  - country+DE-fixed_year+1952-voll+true
  - country+DE-fixed_year+1952-elastic_pwl+default
  - country+DE-fixed_year+1953-inelastic+true
  - country+DE-fixed_year+1953-voll+true
  - country+DE-fixed_year+1953-elastic_pwl+default
  - country+DE-fixed_year+1954-inelastic+true
  - country+DE-fixed_year+1954-voll+true
  - country+DE-fixed_year+1954-elastic_pwl+default
  - country+DE-fixed_year+1955-inelastic+true
  - country+DE-fixed_year+1955-voll+true
  - country+DE-fixed_year+1955-elastic_pwl+default
  - country+DE-fixed_year+1956-inelastic+true
  - country+DE-fixed_year+1956-voll+true
  - country+DE-fixed_year+1956-elastic_pwl+default
  - country+DE-fixed_year+1957-inelastic+true
  - country+DE-fixed_year+1957-voll+true
  - country+DE-fixed_year+1957-elastic_pwl+default
  - country+DE-fixed_year+1958-inelastic+true
  - country+DE-fixed_year+1958-voll+true
  - country+DE-fixed_year+1958-elastic_pwl+default
  - country+DE-fixed_year+1959-inelastic+true
  - country+DE-fixed_year+1959-voll+true
  - country+DE-fixed_year+1959-elastic_pwl+default
  - country+DE-fixed_year+1960-inelastic+true
  - country+DE-fixed_year+1960-voll+true
  - country+DE-fixed_year+1960-elastic_pwl+default
  - country+DE-fixed_year+1961-inelastic+true
  - country+DE-fixed_year+1961-voll+true
  - country+DE-fixed_year+1961-elastic_pwl+default
  - country+DE-fixed_year+1962-inelastic+true
  - country+DE-fixed_year+1962-voll+true
  - country+DE-fixed_year+1962-elastic_pwl+default
  - country+DE-fixed_year+1963-inelastic+true
  - country+DE-fixed_year+1963-voll+true
  - country+DE-fixed_year+1963-elastic_pwl+default
  - country+DE-fixed_year+1964-inelastic+true
  - country+DE-fixed_year+1964-voll+true
  - country+DE-fixed_year+1964-elastic_pwl+default
  - country+DE-fixed_year+1965-inelastic+true
  - country+DE-fixed_year+1965-voll+true
  - country+DE-fixed_year+1965-elastic_pwl+default
  - country+DE-fixed_year+1966-inelastic+true
  - country+DE-fixed_year+1966-voll+true
  - country+DE-fixed_year+1966-elastic_pwl+default
  - country+DE-fixed_year+1967-inelastic+true
  - country+DE-fixed_year+1967-voll+true
  - country+DE-fixed_year+1967-elastic_pwl+default
  - country+DE-fixed_year+1968-inelastic+true
  - country+DE-fixed_year+1968-voll+true
  - country+DE-fixed_year+1968-elastic_pwl+default
  - country+DE-fixed_year+1969-inelastic+true
  - country+DE-fixed_year+1969-voll+true
  - country+DE-fixed_year+1969-elastic_pwl+default
  - country+DE-fixed_year+1970-inelastic+true
  - country+DE-fixed_year+1970-voll+true
  - country+DE-fixed_year+1970-elastic_pwl+default
  - country+DE-fixed_year+1971-inelastic+true
  - country+DE-fixed_year+1971-voll+true
  - country+DE-fixed_year+1971-elastic_pwl+default
  - country+DE-fixed_year+1972-inelastic+true
  - country+DE-fixed_year+1972-voll+true
  - country+DE-fixed_year+1972-elastic_pwl+default
  - country+DE-fixed_year+1973-inelastic+true
  - country+DE-fixed_year+1973-voll+true
  - country+DE-fixed_year+1973-elastic_pwl+default
  - country+DE-fixed_year+1974-inelastic+true
  - country+DE-fixed_year+1974-voll+true
  - country+DE-fixed_year+1974-elastic_pwl+default
  - country+DE-fixed_year+1975-inelastic+true
  - country+DE-fixed_year+1975-voll+true
  - country+DE-fixed_year+1975-elastic_pwl+default
  - country+DE-fixed_year+1976-inelastic+true
  - country+DE-fixed_year+1976-voll+true
  - country+DE-fixed_year+1976-elastic_pwl+default
  - country+DE-fixed_year+1977-inelastic+true
  - country+DE-fixed_year+1977-voll+true
  - country+DE-fixed_year+1977-elastic_pwl+default
  - country+DE-fixed_year+1978-inelastic+true
  - country+DE-fixed_year+1978-voll+true
  - country+DE-fixed_year+1978-elastic_pwl+default
  - country+DE-fixed_year+1979-inelastic+true
  - country+DE-fixed_year+1979-voll+true
  - country+DE-fixed_year+1979-elastic_pwl+default
  - country+DE-fixed_year+1980-inelastic+true
  - country+DE-fixed_year+1980-voll+true
  - country+DE-fixed_year+1980-elastic_pwl+default
  - country+DE-fixed_year+1981-inelastic+true
  - country+DE-fixed_year+1981-voll+true
  - country+DE-fixed_year+1981-elastic_pwl+default
  - country+DE-fixed_year+1982-inelastic+true
  - country+DE-fixed_year+1982-voll+true
  - country+DE-fixed_year+1982-elastic_pwl+default
  - country+DE-fixed_year+1983-inelastic+true
  - country+DE-fixed_year+1983-voll+true
  - country+DE-fixed_year+1983-elastic_pwl+default
  - country+DE-fixed_year+1984-inelastic+true
  - country+DE-fixed_year+1984-voll+true
  - country+DE-fixed_year+1984-elastic_pwl+default
  - country+DE-fixed_year+1985-inelastic+true
  - country+DE-fixed_year+1985-voll+true
  - country+DE-fixed_year+1985-elastic_pwl+default
  - country+DE-fixed_year+1986-inelastic+true
  - country+DE-fixed_year+1986-voll+true
  - country+DE-fixed_year+1986-elastic_pwl+default
  - country+DE-fixed_year+1987-inelastic+true
  - country+DE-fixed_year+1987-voll+true
  - country+DE-fixed_year+1987-elastic_pwl+default
  - country+DE-fixed_year+1988-inelastic+true
  - country+DE-fixed_year+1988-voll+true
  - country+DE-fixed_year+1988-elastic_pwl+default
  - country+DE-fixed_year+1989-inelastic+true
  - country+DE-fixed_year+1989-voll+true
  - country+DE-fixed_year+1989-elastic_pwl+default
  - country+DE-fixed_year+1990-inelastic+true
  - country+DE-fixed_year+1990-voll+true
  - country+DE-fixed_year+1990-elastic_pwl+default
  - country+DE-fixed_year+1991-inelastic+true
  - country+DE-fixed_year+1991-voll+true
  - country+DE-fixed_year+1991-elastic_pwl+default
  - country+DE-fixed_year+1992-inelastic+true
  - country+DE-fixed_year+1992-voll+true
  - country+DE-fixed_year+1992-elastic_pwl+default
  - country+DE-fixed_year+1993-inelastic+true
  - country+DE-fixed_year+1993-voll+true
  - country+DE-fixed_year+1993-elastic_pwl+default
  - country+DE-fixed_year+1994-inelastic+true
  - country+DE-fixed_year+1994-voll+true
  - country+DE-fixed_year+1994-elastic_pwl+default
  - country+DE-fixed_year+1995-inelastic+true
  - country+DE-fixed_year+1995-voll+true
  - country+DE-fixed_year+1995-elastic_pwl+default
  - country+DE-fixed_year+1996-inelastic+true
  - country+DE-fixed_year+1996-voll+true
  - country+DE-fixed_year+1996-elastic_pwl+default
  - country+DE-fixed_year+1997-inelastic+true
  - country+DE-fixed_year+1997-voll+true
  - country+DE-fixed_year+1997-elastic_pwl+default
  - country+DE-fixed_year+1998-inelastic+true
  - country+DE-fixed_year+1998-voll+true
  - country+DE-fixed_year+1998-elastic_pwl+default
  - country+DE-fixed_year+1999-inelastic+true
  - country+DE-fixed_year+1999-voll+true
  - country+DE-fixed_year+1999-elastic_pwl+default
  - country+DE-fixed_year+2000-inelastic+true
  - country+DE-fixed_year+2000-voll+true
  - country+DE-fixed_year+2000-elastic_pwl+default
  - country+DE-fixed_year+2001-inelastic+true
  - country+DE-fixed_year+2001-voll+true
  - country+DE-fixed_year+2001-elastic_pwl+default
  - country+DE-fixed_year+2002-inelastic+true
  - country+DE-fixed_year+2002-voll+true
  - country+DE-fixed_year+2002-elastic_pwl+default
  - country+DE-fixed_year+2003-inelastic+true
  - country+DE-fixed_year+2003-voll+true
  - country+DE-fixed_year+2003-elastic_pwl+default
  - country+DE-fixed_year+2004-inelastic+true
  - country+DE-fixed_year+2004-voll+true
  - country+DE-fixed_year+2004-elastic_pwl+default
  - country+DE-fixed_year+2005-inelastic+true
  - country+DE-fixed_year+2005-voll+true
  - country+DE-fixed_year+2005-elastic_pwl+default
  - country+DE-fixed_year+2006-inelastic+true
  - country+DE-fixed_year+2006-voll+true
  - country+DE-fixed_year+2006-elastic_pwl+default
  - country+DE-fixed_year+2007-inelastic+true
  - country+DE-fixed_year+2007-voll+true
  - country+DE-fixed_year+2007-elastic_pwl+default
  - country+DE-fixed_year+2008-inelastic+true
  - country+DE-fixed_year+2008-voll+true
  - country+DE-fixed_year+2008-elastic_pwl+default
  - country+DE-fixed_year+2009-inelastic+true
  - country+DE-fixed_year+2009-voll+true
  - country+DE-fixed_year+2009-elastic_pwl+default
  - country+DE-fixed_year+2010-inelastic+true
  - country+DE-fixed_year+2010-voll+true
  - country+DE-fixed_year+2010-elastic_pwl+default
  - country+DE-fixed_year+2011-inelastic+true
  - country+DE-fixed_year+2011-voll+true
  - country+DE-fixed_year+2011-elastic_pwl+default
  - country+DE-fixed_year+2012-inelastic+true
  - country+DE-fixed_year+2012-voll+true
  - country+DE-fixed_year+2012-elastic_pwl+default
  - country+DE-fixed_year+2013-inelastic+true
  - country+DE-fixed_year+2013-voll+true
  - country+DE-fixed_year+2013-elastic_pwl+default
  - country+DE-fixed_year+2014-inelastic+true
  - country+DE-fixed_year+2014-voll+true
  - country+DE-fixed_year+2014-elastic_pwl+default
  - country+DE-fixed_year+2015-inelastic+true
  - country+DE-fixed_year+2015-voll+true
  - country+DE-fixed_year+2015-elastic_pwl+default
  - country+DE-fixed_year+2016-inelastic+true
  - country+DE-fixed_year+2016-voll+true
  - country+DE-fixed_year+2016-elastic_pwl+default
  - country+DE-fixed_year+2017-inelastic+true
  - country+DE-fixed_year+2017-voll+true
  - country+DE-fixed_year+2017-elastic_pwl+default
  - country+DE-fixed_year+2018-inelastic+true
  - country+DE-fixed_year+2018-voll+true
  - country+DE-fixed_year+2018-elastic_pwl+default
  - country+DE-fixed_year+2019-inelastic+true
  - country+DE-fixed_year+2019-voll+true
  - country+DE-fixed_year+2019-elastic_pwl+default
  - country+DE-fixed_year+2020-inelastic+true
  - country+DE-fixed_year+2020-voll+true
  - country+DE-fixed_year+2020-elastic_pwl+default
  - country+DE-fixed_year+1951-elastic+true-elastic_intercept+2000
  - country+DE-fixed_year+1952-elastic+true-elastic_intercept+2000
  - country+DE-fixed_year+1953-elastic+true-elastic_intercept+2000
  - country+DE-fixed_year+1954-elastic+true-elastic_intercept+2000
  - country+DE-fixed_year+1955-elastic+true-elastic_intercept+2000
  - country+DE-fixed_year+1956-elastic+true-elastic_intercept+2000
  - country+DE-fixed_year+1957-elastic+true-elastic_intercept+2000
  - country+DE-fixed_year+1958-elastic+true-elastic_intercept+2000
  - country+DE-fixed_year+1959-elastic+true-elastic_intercept+2000
  - country+DE-fixed_year+1960-elastic+true-elastic_intercept+2000
  - country+DE-fixed_year+1961-elastic+true-elastic_intercept+2000
  - country+DE-fixed_year+1962-elastic+true-elastic_intercept+2000
  - country+DE-fixed_year+1963-elastic+true-elastic_intercept+2000
  - country+DE-fixed_year+1964-elastic+true-elastic_intercept+2000
  - country+DE-fixed_year+1965-elastic+true-elastic_intercept+2000
  - country+DE-fixed_year+1966-elastic+true-elastic_intercept+2000
  - country+DE-fixed_year+1967-elastic+true-elastic_intercept+2000
  - country+DE-fixed_year+1968-elastic+true-elastic_intercept+2000
  - country+DE-fixed_year+1969-elastic+true-elastic_intercept+2000
  - country+DE-fixed_year+1970-elastic+true-elastic_intercept+2000
  - country+DE-fixed_year+1971-elastic+true-elastic_intercept+2000
  - country+DE-fixed_year+1972-elastic+true-elastic_intercept+2000
  - country+DE-fixed_year+1973-elastic+true-elastic_intercept+2000
  - country+DE-fixed_year+1974-elastic+true-elastic_intercept+2000
  - country+DE-fixed_year+1975-elastic+true-elastic_intercept+2000
  - country+DE-fixed_year+1976-elastic+true-elastic_intercept+2000
  - country+DE-fixed_year+1977-elastic+true-elastic_intercept+2000
  - country+DE-fixed_year+1978-elastic+true-elastic_intercept+2000
  - country+DE-fixed_year+1979-elastic+true-elastic_intercept+2000
  - country+DE-fixed_year+1980-elastic+true-elastic_intercept+2000
  - country+DE-fixed_year+1981-elastic+true-elastic_intercept+2000
  - country+DE-fixed_year+1982-elastic+true-elastic_intercept+2000
  - country+DE-fixed_year+1983-elastic+true-elastic_intercept+2000
  - country+DE-fixed_year+1984-elastic+true-elastic_intercept+2000
  - country+DE-fixed_year+1985-elastic+true-elastic_intercept+2000
  - country+DE-fixed_year+1986-elastic+true-elastic_intercept+2000
  - country+DE-fixed_year+1987-elastic+true-elastic_intercept+2000
  - country+DE-fixed_year+1988-elastic+true-elastic_intercept+2000
  - country+DE-fixed_year+1989-elastic+true-elastic_intercept+2000
  - country+DE-fixed_year+1990-elastic+true-elastic_intercept+2000
  - country+DE-fixed_year+1991-elastic+true-elastic_intercept+2000
  - country+DE-fixed_year+1992-elastic+true-elastic_intercept+2000
  - country+DE-fixed_year+1993-elastic+true-elastic_intercept+2000
  - country+DE-fixed_year+1994-elastic+true-elastic_intercept+2000
  - country+DE-fixed_year+1995-elastic+true-elastic_intercept+2000
  - country+DE-fixed_year+1996-elastic+true-elastic_intercept+2000
  - country+DE-fixed_year+1997-elastic+true-elastic_intercept+2000
  - country+DE-fixed_year+1998-elastic+true-elastic_intercept+2000
  - country+DE-fixed_year+1999-elastic+true-elastic_intercept+2000
  - country+DE-fixed_year+2000-elastic+true-elastic_intercept+2000
  - country+DE-fixed_year+2001-elastic+true-elastic_intercept+2000
  - country+DE-fixed_year+2002-elastic+true-elastic_intercept+2000
  - country+DE-fixed_year+2003-elastic+true-elastic_intercept+2000
  - country+DE-fixed_year+2004-elastic+true-elastic_intercept+2000
  - country+DE-fixed_year+2005-elastic+true-elastic_intercept+2000
  - country+DE-fixed_year+2006-elastic+true-elastic_intercept+2000
  - country+DE-fixed_year+2007-elastic+true-elastic_intercept+2000
  - country+DE-fixed_year+2008-elastic+true-elastic_intercept+2000
  - country+DE-fixed_year+2009-elastic+true-elastic_intercept+2000
  - country+DE-fixed_year+2010-elastic+true-elastic_intercept+2000
  - country+DE-fixed_year+2011-elastic+true-elastic_intercept+2000
  - country+DE-fixed_year+2012-elastic+true-elastic_intercept+2000
  - country+DE-fixed_year+2013-elastic+true-elastic_intercept+2000
  - country+DE-fixed_year+2014-elastic+true-elastic_intercept+2000
  - country+DE-fixed_year+2015-elastic+true-elastic_intercept+2000
  - country+DE-fixed_year+2016-elastic+true-elastic_intercept+2000
  - country+DE-fixed_year+2017-elastic+true-elastic_intercept+2000
  - country+DE-fixed_year+2018-elastic+true-elastic_intercept+2000
  - country+DE-fixed_year+2019-elastic+true-elastic_intercept+2000
  - country+DE-fixed_year+2020-elastic+true-elastic_intercept+2000
  st: []

snapshots:
  start: "1951-01-01"
  end: "2021-01-01"

solver:
  mem_mb: 4000
  walltime: 2h
