run: trial

country: DE

load: 100 # MW

voll: false
elastic: true
inelastic: false

wind: true
solar: true

hydrogen: true
battery: true

elastic_intercept: 2000 # €/MWh
voll_price: 2000 # €/MWh

technology_data:
  year: 2030
  version: v0.6.0
  fill_values:
    FOM: 0
    VOM: 0
    efficiency: 1
    investment: 0
    lifetime: 25
    discount rate: 0.07

snapshots:
  start: "2010-01-01"
  end: "2011-01-01"
  inclusive: left
  freq: 1H

solver:
  name: gurobi
  options: gurobi-default

solver_options:
  gurobi-default:
    threads: 4
    method: 2 # barrier
    crossover: 0
    BarConvTol: 1.e-6
    Seed: 123
    AggFill: 0
    PreDual: 0
    GURO_PAR_BARDENSETHRESH: 200
    seed: 10


colors:
  wind : blue
  solar: yellow
  battery: grey
  battery storage: grey
  battery charger: grey
  battery discharger: grey
  hydrogen: cyan
  hydrogen fuel cell: red
  hydrogen electrolyser: cyan
  hydrogen underground storage: magenta
  electricity: black
  load: black