name: price-formation
channels:
- conda-forge
- bioconda
- gurobi
dependencies:
- python==3.11
- pip
- pypsa==0.27.1
- linopy>=0.3.8
- snakemake-minimal>=8.5
- pandas
- numpy
- xarray
- netcdf4
- matplotlib
- country_converter
- graphviz
- ipython
- gurobi
- ipykernel
- seaborn
- jupyterlab
- pre-commit
- snakemake-storage-plugin-http
- snakemake-executor-plugin-cluster-generic

- pip:
  - highspy
